# 필요한거 설치해주기

In [ ]:
!pip install tensorflow

In [ ]:
pip install keras

#  keras import 해주고 시작함

In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, LSTM
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
Test1 = pd.read_excel("Final_V4.xlsx")

In [ ]:
x1 = Test1.drop(['ZONE','Dong','SEQ','DISTRICT','DIST','Unnamed: 0','ADM_CD','F_BEGIN_DE','F_END_DE','F_BEGIN_TM','F_END_TM','FLUD_TIME','PRECI_HH'], axis= 1)
x2 = Test1['DIST']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x1, x2, test_size=0.3, random_state=100)
print(len(X_train), len(X_test),len(y_train),len(y_test))

In [ ]:
model = Sequential()
model.add(LSTM(10, activation= 'relu', input_shape = (9,1)))

In [ ]:
model.add(Dense(5))
model.add(Dense(1))

In [ ]:
model.summary()

In [ ]:
# model.compile(optimizer = 'adam', loss='mse')
model.fit(X_train, y_train, epochs=100, batch_size=1)

# 잘 안되서 다른방식으로 해봄

In [3]:
Test1 = pd.read_excel("Final_V4.xlsx")

In [4]:
x1 = Test1.drop(['ZONE','Dong','SEQ','DISTRICT','DIST','Unnamed: 0','ADM_CD','F_BEGIN_DE','F_END_DE','F_BEGIN_TM','F_END_TM','FLUD_TIME','PRECI_HH'], axis= 1)
x2 = Test1['DIST']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x1, x2, test_size=0.3, random_state=100)
print(len(X_train), len(X_test),len(y_train),len(y_test))

1192 512 1192 512


# 정규화 안한거랑 한거랑 둘다 해볼거

## 아래 과정은 다시 ndarray로 변환해서 deep learning 모델에 사용되는 형태로 바꿔줌

In [6]:

X_train = X_train.values
X_test= X_test.values

y_train = y_train.values
y_test = y_test.values
print(X_train.shape)
print(X_train)
print(y_train.shape)
print(y_train)

# X_train.shape를 프린트해줘서 형태를 확인가능
#나중에 데이터 형식 바꿀때 쓰는거

(1192, 10)
[[0.00000000e+00 1.50000000e+01 3.00000000e+01 ... 1.63868313e-02
  5.30000000e+01 2.01408250e+07]
 [0.00000000e+00 1.50000000e+01 3.00000000e+01 ... 1.76841435e-02
  1.60000000e+00 2.01610050e+07]
 [1.04000000e-01 0.00000000e+00 2.00000000e+00 ... 1.30827068e-02
  2.25000000e+01 2.01107270e+07]
 ...
 [8.40000000e-01 0.00000000e+00 2.00000000e+00 ... 6.94396365e-03
  1.58000000e+01 2.01907190e+07]
 [0.00000000e+00 7.00000000e+00 1.50000000e+01 ... 6.94396365e-03
  2.00000000e+00 2.01209160e+07]
 [0.00000000e+00 7.00000000e+00 1.50000000e+01 ... 1.63868313e-02
  2.00000000e-01 2.00907140e+07]]
(1192,)
[0 0 1 ... 1 0 0]


   ## keras 는 RNN 계열 모델을 트레이닝 하기위해  데이터 형식( 3차원)을 요구함

In [13]:
X_train_t = X_train.reshape(X_train.shape[0], 10, 1)
X_test_t = X_test.reshape(X_test.shape[0], 10, 1)

print(X_train_t.shape)
# print(X_train_t)
print(y_train.shape)

(1192, 10, 1)
(1192,)


In [15]:
from keras.layers import LSTM 
from keras.models import Sequential
from keras.layers import Dense
import keras.backend as K 
from keras.callbacks import EarlyStopping



In [19]:
K.clear_session() 
model = Sequential() 
model.add(LSTM(20, input_shape=(10, 1))) 
model.add(Dense(1)) 
model.compile(loss='mean_squared_error', optimizer='adam') 

# 일반적인 optimizer 는 아담임
# 예측하는 타겟의 갯수는 DIST 1개니까 DENSE는 1로줌

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 20)                1760      
_________________________________________________________________
dense (Dense)                (None, 1)                 21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________


In [21]:
early_stop = EarlyStopping(monitor='loss', patience=1, verbose=1)
# 이 객체를 이용해 poch 마다 early stopping 체크한다.
# early stopping 는 무조건 epoch 를 마구 돌린후 특정시점에서 멈추게하는거

In [22]:
model.fit(X_train_t, y_train, epochs=100, batch_size=30,
          verbose=1, callbacks=[early_stop])

Epoch 1/100
40/40 [==============================] - 0s 3ms/step - loss: 0.2050
Epoch 2/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1747
Epoch 3/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1530
Epoch 4/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1228
Epoch 5/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1207
Epoch 6/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1117
Epoch 7/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1072
Epoch 8/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1037
Epoch 9/100
40/40 [==============================] - 0s 2ms/step - loss: 0.1002
Epoch 10/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0966
Epoch 11/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0933
Epoch 12/100
40/40 [==============================] - 0s 2ms/step - loss: 0.0899
Epoch 13/100
40/40 [=================

In [23]:
print(X_test_t)

[[[4.00000000e-01]
  [0.00000000e+00]
  [2.00000000e+00]
  ...
  [2.38850347e-02]
  [3.04000000e+01]
  [2.01709110e+07]]

 [[3.50000000e-01]
  [1.50000000e+01]
  [3.00000000e+01]
  ...
  [6.94396365e-03]
  [2.40000000e+01]
  [2.01209130e+07]]

 [[0.00000000e+00]
  [1.50000000e+01]
  [3.00000000e+01]
  ...
  [1.63868313e-02]
  [1.95000000e+01]
  [2.01709110e+07]]

 ...

 [[0.00000000e+00]
  [1.50000000e+01]
  [3.00000000e+01]
  ...
  [1.68081040e-02]
  [0.00000000e+00]
  [2.01408250e+07]]

 [[0.00000000e+00]
  [7.00000000e+00]
  [1.50000000e+01]
  ...
  [1.68081040e-02]
  [7.80000000e+01]
  [2.00907160e+07]]

 [[5.50000000e-01]
  [0.00000000e+00]
  [2.00000000e+00]
  ...
  [1.39393103e-02]
  [5.30000000e+01]
  [2.01408250e+07]]]


In [24]:
y_pred = model.predict(X_test_t)
print(y_pred)

[[ 9.75046694e-01]
 [ 8.37581217e-01]
 [-4.73707132e-02]
 [ 1.02345610e+00]
 [-3.42867337e-02]
 [ 9.85828817e-01]
 [ 8.60418379e-01]
 [ 1.00068951e+00]
 [-6.47737533e-02]
 [-6.32753670e-02]
 [ 9.28927839e-01]
 [-5.56193553e-02]
 [ 9.28613916e-03]
 [-6.40906394e-02]
 [-6.77294731e-02]
 [-2.88049318e-02]
 [-4.22633551e-02]
 [-5.26796989e-02]
 [ 1.00325072e+00]
 [ 9.74202335e-01]
 [-2.32323222e-02]
 [ 9.97976840e-01]
 [-1.82830952e-02]
 [-7.07962811e-02]
 [ 9.66989458e-01]
 [ 9.78529155e-01]
 [-1.29924193e-01]
 [-5.80120943e-02]
 [ 8.77058566e-01]
 [-8.13317299e-02]
 [-1.10447690e-01]
 [ 9.35491979e-01]
 [-3.62358987e-05]
 [-1.36661038e-01]
 [-5.80365583e-03]
 [-3.80642973e-02]
 [-4.05991189e-02]
 [-6.40906394e-02]
 [ 1.02019274e+00]
 [ 9.73444059e-03]
 [ 1.00748301e-01]
 [-4.12159823e-02]
 [-5.21268696e-04]
 [ 1.03016222e+00]
 [-8.16870108e-03]
 [ 1.07113862e+00]
 [-6.40906394e-02]
 [ 9.10256505e-01]
 [ 1.16482712e-02]
 [-1.41107105e-02]
 [ 1.04190755e+00]
 [-2.57623009e-02]
 [ 1.2353483

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

report = classification_report(y_test, y_pred)
print(report)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [26]:
print(model.score(X_train, y_train)) #

print(model.score(X_test, y_test))

AttributeError: 'Sequential' object has no attribute 'score'